Repository brainhubeu/react-carousel, pull requests merged in 2020-07, with the labels that each got.

#584 Fix error: Failed to execute 'observe' on 'ResizeObserver': parameter…
  src/components/CarouselItem.js
Labels: tested & works

#532 Fix/pr 531 ndeviant master
  README.md
  docs-www/gatsby-docs-kit.yml
  docs/api/carousel.md
  docs/examples/lazyload.md
  src/components/Carousel.js
  src/styles/Carousel.scss
  test/unit/carousel.test.js
Labels: tested & works

#545 Fix/pr 544 my mooc feature add onInit callback
  README.md
  docs/api/carousel.md
  src/components/Carousel.js
Labels: tested & works

#594 Fix/pr 593 mhatvan 394 setting offset breaks centered
  src/components/CarouselItem.js
Labels: tested & works

#610 Fix/pr 605 fubinator fix google lighthouse passive event listeners
  src/components/Carousel.js
Labels: v1

#613 Fix: set event listeners to be passive for the lighthouse audit
  react-carousel/src/components/Carousel.js
  react-carousel/src/hooks/useEventListener.js
Labels: v2

#614 ci: automate releasing, publishing release notes, unify commit messages
  .circleci/config.yml
  .releaserc
  commitlint.config.js
  docs/contributions-guide/workflow.md
  license/blacklist.js
  license/whitelist.js
  package.json
  tools/deploy-gh-pages-pr.sh
  tools/deploy-gh-pages.sh
  yarn.lock
Labels: v2

#611 Fix rendering carousel when one of the carousel children is an array of react elements
  src/components/CarouselItem.js
  test/unit/carousel.test.js
Labels: v1

#612 Fix rendering carousel when one of the carousel children is an array of react elements
  docs-www/package.json
  react-carousel/src/components/CarouselSlide.js
  react-carousel/test/carousel.test.js
Labels: v2
